[package]
name = "insert_digit_anywhere_primes_constant"
version = "0.1.0"
authors = ["William Ball <wball1@swarthmore.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_prime = "1.0.5"
rand = "0.7.3"
